# Form implementation generated from reading ui file 'addAccount.ui'
#
# Created by: PyQt5 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

"""
**************************************************
@IDE    ：PyCharm
@Author ：Yuzhii0718,You3697
@Update ：2023/12/7 9:42
**************************************************
"""

from PyQt5 import QtCore, QtGui, QtWidgets

import mysql.connector as mc
from PyQt5.QtWidgets import QMessageBox

from .adminInfo import get_admin_account, get_admin_password, log_status


class addAccount_Dialog(object):
    def __init__(self):
        super().__init__()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 350)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_accountName = QtWidgets.QLabel(parent=Dialog)
        self.label_accountName.setObjectName("label_accountName")
        self.horizontalLayout.addWidget(self.label_accountName)
        self.lineEdit_accountName = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_accountName.setFont(font)
        self.lineEdit_accountName.setObjectName("lineEdit_accountName")
        self.horizontalLayout.addWidget(self.lineEdit_accountName)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_accountID = QtWidgets.QLabel(parent=Dialog)
        self.label_accountID.setObjectName("label_accountID")
        self.horizontalLayout_2.addWidget(self.label_accountID)
        self.lineEdit_accountID = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_accountID.setFont(font)
        self.lineEdit_accountID.setObjectName("lineEdit_accountID")
        self.horizontalLayout_2.addWidget(self.lineEdit_accountID)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_accountPhone = QtWidgets.QLabel(parent=Dialog)
        self.label_accountPhone.setObjectName("label_accountPhone")
        self.horizontalLayout_3.addWidget(self.label_accountPhone)
        self.lineEdit_accountPhone = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_accountPhone.setFont(font)
        self.lineEdit_accountPhone.setObjectName("lineEdit_accountPhone")
        self.horizontalLayout_3.addWidget(self.lineEdit_accountPhone)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.label_accountEmail = QtWidgets.QLabel(parent=Dialog)
        self.label_accountEmail.setObjectName("label_accountEmail")
        self.horizontalLayout_4.addWidget(self.label_accountEmail)
        self.lineEdit_accountEmail = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_accountEmail.setFont(font)
        self.lineEdit_accountEmail.setObjectName("lineEdit_accountEmail")
        self.horizontalLayout_4.addWidget(self.lineEdit_accountEmail)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.pushButton_addAccount = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_addAccount.setObjectName("pushButton_addAccount")
        self.horizontalLayout_5.addWidget(self.pushButton_addAccount)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.label_actionStatus = QtWidgets.QLabel(parent=Dialog)
        self.label_actionStatus.setText("")
        self.label_actionStatus.setObjectName("label_actionStatus")
        self.horizontalLayout_6.addWidget(self.label_actionStatus)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem18)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # 信号与槽
        self.pushButton_addAccount.clicked.connect(self.insert_account)

    def insert_account(self):
        try:
            admin_username = get_admin_account()
            admin_password = get_admin_password()
            if log_status() is False:
                QMessageBox.critical(self.pushButton_addAccount, "错误", "请先登录！")
                self.label_actionStatus.setText("请先登录！")
                self.label_actionStatus.setStyleSheet("color: rgb(255, 0, 0);")
                return

            mydatabase = mc.connect(
                host="localhost",
                user="{}".format(admin_username),
                password="{}".format(admin_password),
                database="library"
            )

            tablename = "tbl_addaccount"

            name = self.lineEdit_accountName.text()
            accountID = self.lineEdit_accountID.text()
            phone = self.lineEdit_accountPhone.text()
            email = self.lineEdit_accountEmail.text()

            # 如果有一个为空，则不插入
            if name == "" or accountID == "" or phone == "" or email == "":
                QMessageBox.critical(self.pushButton_addAccount, "错误", "请填写完整信息！")
                self.label_actionStatus.setText("请填写完整信息！")
                self.label_actionStatus.setStyleSheet("color: rgb(200, 150, 0);")
                return

            mycursor = mydatabase.cursor()
            sql = "INSERT INTO {} (name, accountID, phone, email) VALUES (%s, %s, %s, %s)".format(tablename)
            val = (name, accountID, phone, email)
            mycursor.execute(sql, val)
            mydatabase.commit()
            print(mycursor.rowcount, "记录插入成功。")

            mycursor.close()
            mydatabase.close()
            QMessageBox.information(self.pushButton_addAccount, "提示", "记录插入成功！")
            self.label_actionStatus.setText("记录插入成功！")
            self.label_actionStatus.setStyleSheet("color: rgb(0, 200, 0);")
            # 清空输入框
            self.lineEdit_accountName.setText("")
            self.lineEdit_accountID.setText("")
            self.lineEdit_accountPhone.setText("")
            self.lineEdit_accountEmail.setText("")

        except mc.Error as e:
            print("记录添加失败：", e)
            QMessageBox.critical(self.pushButton_addAccount, "错误", "记录添加失败！")
            # 输出 e.args 的内容
            self.label_actionStatus.setText(e.args[1])
            self.label_actionStatus.setStyleSheet("color: rgb(200, 0, 0);")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_accountName.setText(_translate("Dialog", "📛姓名"))
        self.lineEdit_accountName.setPlaceholderText(_translate("Dialog", "请输入姓名..."))
        self.label_accountID.setText(_translate("Dialog", "🪪编号"))
        self.lineEdit_accountID.setPlaceholderText(_translate("Dialog", "请输入编号..."))
        self.label_accountPhone.setText(_translate("Dialog", "☎️电话"))
        self.lineEdit_accountPhone.setPlaceholderText(_translate("Dialog", "请输入电话..."))
        self.label_accountEmail.setText(_translate("Dialog", "📧邮箱"))
        self.lineEdit_accountEmail.setPlaceholderText(_translate("Dialog", "请输入邮箱..."))
        self.pushButton_addAccount.setText(_translate("Dialog", "➕添加账号"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = addAccount_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
