# Form implementation generated from reading ui file 'addBook.ui'
#
# Created by: PyQt5 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

"""
**************************************************
@IDE    ：PyCharm
@Author ：Yuzhii0718,You3697
@Update ：2023/12/7 9:38
**************************************************
"""

from PyQt5 import QtCore, QtGui, QtWidgets

import mysql.connector as mc
from PyQt5.QtWidgets import QMessageBox

from .adminInfo import get_admin_account, get_admin_password, log_status


class addBook_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 350)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_bookTitle = QtWidgets.QLabel(parent=Dialog)
        self.label_bookTitle.setObjectName("label_bookTitle")
        self.horizontalLayout.addWidget(self.label_bookTitle)
        self.lineEdit_bookTitle = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_bookTitle.setFont(font)
        self.lineEdit_bookTitle.setObjectName("lineEdit_bookTitle")
        self.horizontalLayout.addWidget(self.lineEdit_bookTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_bookID = QtWidgets.QLabel(parent=Dialog)
        self.label_bookID.setObjectName("label_bookID")
        self.horizontalLayout_2.addWidget(self.label_bookID)
        self.lineEdit_bookID = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_bookID.setFont(font)
        self.lineEdit_bookID.setObjectName("lineEdit_bookID")
        self.horizontalLayout_2.addWidget(self.lineEdit_bookID)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.label_bookAuthor = QtWidgets.QLabel(parent=Dialog)
        self.label_bookAuthor.setObjectName("label_bookAuthor")
        self.horizontalLayout_3.addWidget(self.label_bookAuthor)
        self.lineEdit_bookAuthor = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_bookAuthor.setFont(font)
        self.lineEdit_bookAuthor.setObjectName("lineEdit_bookAuthor")
        self.horizontalLayout_3.addWidget(self.lineEdit_bookAuthor)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.label_bookPublisher = QtWidgets.QLabel(parent=Dialog)
        self.label_bookPublisher.setObjectName("label_bookPublisher")
        self.horizontalLayout_4.addWidget(self.label_bookPublisher)
        self.lineEdit_bookPublisher = QtWidgets.QLineEdit(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(12)
        self.lineEdit_bookPublisher.setFont(font)
        self.lineEdit_bookPublisher.setObjectName("lineEdit_bookPublisher")
        self.horizontalLayout_4.addWidget(self.lineEdit_bookPublisher)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.pushButton_addBook = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_addBook.setObjectName("pushButton_addBook")
        self.horizontalLayout_5.addWidget(self.pushButton_addBook)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.label_actionStatus = QtWidgets.QLabel(parent=Dialog)
        self.label_actionStatus.setObjectName("label_actionStatus")
        self.horizontalLayout_6.addWidget(self.label_actionStatus)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                             QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem18)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # 信号与槽
        self.pushButton_addBook.clicked.connect(self.insert_book)

    def insert_book(self):
        try:
            admin_username = get_admin_account()
            admin_password = get_admin_password()

            if log_status() is False:
                QMessageBox.critical(self.pushButton_addBook, "错误", "请先登录！")
                self.label_actionStatus.setText("请先登录！")
                self.label_actionStatus.setStyleSheet("color: rgb(255, 0, 0);")
                return

            mydatabase = mc.connect(
                host="localhost",
                user="{}".format(admin_username),
                password="{}".format(admin_password),
                database="library"
            )

            tablename = "tbl_addbook"

            title = self.lineEdit_bookTitle.text()
            bookID = self.lineEdit_bookID.text()
            author = self.lineEdit_bookAuthor.text()
            publisher = self.lineEdit_bookPublisher.text()

            # 如果有一个为空，则不插入
            if title == "" or bookID == "" or author == "" or publisher == "":
                QMessageBox.critical(self.pushButton_addBook, "错误", "请填写完整信息！")
                self.label_actionStatus.setText("请填写完整信息！")
                self.label_actionStatus.setStyleSheet("color: rgb(200, 150, 0);")
                return

            mycursor = mydatabase.cursor()
            sql = "INSERT INTO {} (title, bookID, author, publisher) VALUES (%s, %s, %s, %s)".format(tablename)
            val = (title, bookID, author, publisher)
            mycursor.execute(sql, val)
            mydatabase.commit()
            print(mycursor.rowcount, "记录插入成功。")

            mycursor.close()
            mydatabase.close()
            QMessageBox.information(self.pushButton_addBook, "提示", "记录插入成功！")
            self.label_actionStatus.setText("记录插入成功！")
            self.label_actionStatus.setStyleSheet("color: rgb(0, 200, 0);")
            # 清空输入框
            self.lineEdit_bookTitle.setText("")
            self.lineEdit_bookID.setText("")
            self.lineEdit_bookAuthor.setText("")
            self.lineEdit_bookPublisher.setText("")

        except mc.Error as e:
            print("记录添加失败：", e)
            QMessageBox.critical(self.pushButton_addBook, "错误", "记录添加失败！")
            # 输出 e.args 的内容
            self.label_actionStatus.setText(e.args[1])
            self.label_actionStatus.setStyleSheet("color: rgb(200, 0, 0);")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_bookTitle.setText(_translate("Dialog", "📚标题"))
        self.lineEdit_bookTitle.setPlaceholderText(_translate("Dialog", "请输入书籍标题..."))
        self.label_bookID.setText(_translate("Dialog", "🪪编号"))
        self.lineEdit_bookID.setPlaceholderText(_translate("Dialog", "请输入书籍编号..."))
        self.label_bookAuthor.setText(_translate("Dialog", "✒️作者"))
        self.lineEdit_bookAuthor.setPlaceholderText(_translate("Dialog", "请输入书籍作者..."))
        self.label_bookPublisher.setText(_translate("Dialog", "🖨️出版社"))
        self.lineEdit_bookPublisher.setPlaceholderText(_translate("Dialog", "请输入书籍出版社..."))
        self.pushButton_addBook.setText(_translate("Dialog", "➕添加书籍"))
        self.label_actionStatus.setText(_translate("Dialog", ""))

# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = addBook_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec())
